export const filterCategories = {
  all: [
    { id: "javascript", label: "JavaScript", type: "language" },
    { id: "python", label: "Python", type: "language" },
    { id: "java", label: "Java", type: "language" },
    { id: "react", label: "React", type: "topic" },
    { id: "vue", label: "Vue.js", type: "topic" },
    { id: "angular", label: "Angular", type: "topic" },
    { id: "nodejs", label: "Node.js", type: "topic" },
    { id: "machine-learning", label: "Machine Learning", type: "topic" },
    { id: "artificial-intelligence", label: "AI", type: "topic" },
    { id: "docker", label: "Docker", type: "topic" },
    { id: "kubernetes", label: "Kubernetes", type: "topic" },
  ],
  web: [
    { id: "react", label: "React", type: "topic" },
    { id: "nextjs", label: "Next.js", type: "topic" },
    { id: "vue", label: "Vue.js", type: "topic" },
    { id: "angular", label: "Angular", type: "topic" },
    { id: "svelte", label: "Svelte", type: "topic" },
    { id: "nodejs", label: "Node.js", type: "topic" },
    { id: "express", label: "Express.js", type: "topic" },
    { id: "typescript", label: "TypeScript", type: "language" },
    { id: "javascript", label: "JavaScript", type: "language" },
    { id: "html", label: "HTML", type: "language" },
    { id: "css", label: "CSS", type: "language" },
  ],
  android: [
    { id: "kotlin", label: "Kotlin", type: "language" },
    { id: "java", label: "Java", type: "language" },
    { id: "flutter", label: "Flutter", type: "topic" },
    { id: "react-native", label: "React Native", type: "topic" },
    { id: "xamarin", label: "Xamarin", type: "topic" },
    { id: "android", label: "Android", type: "topic" },
    { id: "mobile", label: "Mobile", type: "topic" },
  ],
  ios: [
    { id: "swift", label: "Swift", type: "language" },
    { id: "swiftui", label: "SwiftUI", type: "topic" },
    { id: "uikit", label: "UIKit", type: "topic" },
    { id: "objective-c", label: "Objective-C", type: "language" },
    { id: "ios", label: "iOS", type: "topic" },
    { id: "mobile", label: "Mobile", type: "topic" },
    { id: "xcode", label: "Xcode", type: "topic" },
  ],
  ai: [
    { id: "tensorflow", label: "TensorFlow", type: "topic" },
    { id: "pytorch", label: "PyTorch", type: "topic" },
    { id: "scikit-learn", label: "Scikit-learn", type: "topic" },
    { id: "keras", label: "Keras", type: "topic" },
    { id: "opencv", label: "OpenCV", type: "topic" },
    { id: "pandas", label: "Pandas", type: "topic" },
    { id: "numpy", label: "NumPy", type: "topic" },
    { id: "jupyter", label: "Jupyter", type: "topic" },
    { id: "machine-learning", label: "Machine Learning", type: "topic" },
    { id: "artificial-intelligence", label: "AI", type: "topic" },
    { id: "deep-learning", label: "Deep Learning", type: "topic" },
    { id: "python", label: "Python", type: "language" },
  ],
  networking: [
    { id: "socketio", label: "Socket.io", type: "topic" },
    { id: "graphql", label: "GraphQL", type: "topic" },
    { id: "rest-api", label: "REST API", type: "topic" },
    { id: "grpc", label: "gRPC", type: "topic" },
    { id: "webrtc", label: "WebRTC", type: "topic" },
    { id: "nginx", label: "Nginx", type: "topic" },
    { id: "api", label: "API", type: "topic" },
    { id: "websocket", label: "WebSocket", type: "topic" },
  ],
  database: [
    { id: "postgresql", label: "PostgreSQL", type: "topic" },
    { id: "mysql", label: "MySQL", type: "topic" },
    { id: "mongodb", label: "MongoDB", type: "topic" },
    { id: "redis", label: "Redis", type: "topic" },
    { id: "sqlite", label: "SQLite", type: "topic" },
    { id: "firebase", label: "Firebase", type: "topic" },
    { id: "database", label: "Database", type: "topic" },
    { id: "sql", label: "SQL", type: "language" },
  ],
  cloud: [
    { id: "aws", label: "AWS", type: "topic" },
    { id: "google-cloud", label: "Google Cloud", type: "topic" },
    { id: "azure", label: "Azure", type: "topic" },
    { id: "docker", label: "Docker", type: "topic" },
    { id: "kubernetes", label: "Kubernetes", type: "topic" },
    { id: "terraform", label: "Terraform", type: "topic" },
    { id: "cloud", label: "Cloud", type: "topic" },
    { id: "devops", label: "DevOps", type: "topic" },
  ],
  gaming: [
    { id: "unity", label: "Unity", type: "topic" },
    { id: "unreal-engine", label: "Unreal Engine", type: "topic" },
    { id: "godot", label: "Godot", type: "topic" },
    { id: "csharp", label: "C#", type: "language" },
    { id: "cpp", label: "C++", type: "language" },
    { id: "blender", label: "Blender", type: "topic" },
    { id: "game-development", label: "Game Development", type: "topic" },
    { id: "3d", label: "3D", type: "topic" },
  ],
};